/**
 * scripts/gen-version.mjs
 *
 * Reads the version from package.json and writes src/version.ts so that
 * `bun build --compile` (which cannot read external files at runtime) embeds
 * the correct version string directly in the binary.
 *
 * Called automatically by the pkg:* scripts before bun compiles.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, '..', 'package.json'), 'utf8'));
const version = pkg.version ?? '0.0.0';

const outPath = join(__dirname, '..', 'src', 'version.ts');
const content = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Regenerated automatically before every pkg:* build.
export const VERSION = '${version}';
`;

writeFileSync(outPath, content, 'utf8');
console.log(`✓ src/version.ts → ${version}`);
